name: Generate Pacman Contribution Graph

on:
  push:  # Trigger on pushes to any branch in Alex807 repo
    branches:
      - '**'  # Matches all branches (main, output, feature branches, etc.)
  workflow_dispatch:  # Keep manual trigger as a backup
  schedule:  # Fallback to ensure updates if you don’t push to Alex807 often
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate Pacman Graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          username: Alex807  # Your GitHub username
          output: output      # Folder to save SVGs
          theme: github      # GitHub’s default theme (or try 'github-dark')
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
